name: Broadcaster
main: com.tetra.broadcaster.Broadcaster
version: 2.0.0rb
author: [Mastershake71]
commands:
   shout:
      description: Broadcasts a message to the server. Usable once every 30 minutes.
      permission: broadcaster.broadcast
      usage: /shout <message>
   apb:
      description: Sends an admin broadcast/alert message.
      permission: broadcaster.staff
      usage: /apb <message>